<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>PipelineBuilder.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PipelineBuilder.Core\PipelineBuilder.Core.csproj" />
  </ItemGroup>
</Project>
