<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SimlifiezYaml.Core\SimlifiezYaml.Core.csproj" />
    <ProjectReference Include="..\..\src\SimlifiezYaml.Web\SimlifiezYaml.Web.csproj" />
  </ItemGroup>
</Project>
